<a href="https://colab.research.google.com/github/apurvakumbhar/ANN/blob/main/LLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Step 1: Dataset
# Features: [rooms, area, location_index]
X = np.array([
    [2, 1200, 0.5],
    [3, 1500, 0.7],
    [4, 1800, 0.9],
    [3, 1600, 0.6],
    [5, 2000, 1.0]
])

# Target (house price)
Y = np.array([[25000], [30000], [40000], [32000], [50000]])

# Step 2: Add bias (1) to each row of X
ones = np.ones((X.shape[0], 1))        # column of 1s
X_b = np.hstack((ones, X))             # shape becomes (5, 4)

# Step 3: Calculate weights using LLS formula
# w = (X^T * X)^-1 * X^T * Y
X_T = X_b.T                            # Transpose
w = np.linalg.inv(X_T @ X_b) @ X_T @ Y

# Step 4: Prediction using weights
Y_pred = X_b @ w

# Step 5: Print results
print("Weights (including bias):\n", w)
print("\nPredicted Prices:\n", Y_pred)

Weights (including bias):
 [[ 2.00000000e+04]
 [ 1.56666667e+04]
 [-1.50000000e+01]
 [-1.83333333e+04]]

Predicted Prices:
 [[24166.66666666]
 [31666.66666666]
 [39166.66666666]
 [31999.99999999]
 [49999.99999999]]


In [ ]:
from sklearn.linear_model import Ridge, Lasso
from sklearn.metrics import mean_squared_error

# Normalize X (so that all features are on similar scale)
X_mean = np.mean(X, axis=0)
X_std = np.std(X, axis=0)
X_norm = (X - X_mean) / X_std

# Ridge Regression
ridge = Ridge(alpha=1.0)
ridge.fit(X_norm, Y)
Y_ridge_pred = ridge.predict(X_norm)

# Lasso Regression
lasso = Lasso(alpha=0.1)
lasso.fit(X_norm, Y)
Y_lasso_pred = lasso.predict(X_norm)

# MSE for both
print("Ridge Predicted Prices:\n", Y_ridge_pred)
print("\nMSE (Ridge):", mean_squared_error(Y, Y_ridge_pred))
print("\n")


print("Lasso Predicted Prices:\n", Y_lasso_pred)
print("\nMSE (Lasso):", mean_squared_error(Y, Y_lasso_pred))

Ridge Predicted Prices:
 [23970.89854524 32482.84741097 40994.79627671 32223.94014917
 47327.51761791]

MSE (Ridge): 3081102.395104151


Lasso Predicted Prices:
 [24165.0969703  31667.36828728 39169.63960427 32000.46083013
 49997.43430802]

MSE (Lasso): 833337.0512765141


In [ ]:
# Initialize random weights and bias
w = np.random.rand(3, 1)
b = np.random.rand(1)
lr = 0.01
epochs = 1000

# Gradient Descent
for i in range(epochs):
    y_pred = np.dot(X_norm, w) + b
    error = y_pred - Y

    dw = np.dot(X_norm.T, error) / len(Y)
    db = np.sum(error) / len(Y)

    w -= lr * dw
    b -= lr * db


Y_gd_pred = np.dot(X_norm, w) + b

print("\nGradient Descent Predicted Prices:\n", Y_gd_pred)
print("MSE (Gradient Descent):", mean_squared_error(Y, Y_gd_pred))



Gradient Descent Predicted Prices:
 [[23185.72828997]
 [32220.9415511 ]
 [41256.15481223]
 [32118.23101267]
 [48211.30305019]]
MSE (Gradient Descent): 2603100.6948188352
